### ISSUE TITLE
Dev (Ctrl+Shift) info is not work

### ISSUE THREAD

**Issue by hiop** [Nightdawg/Hurricane#7]
https://github.com/Nightdawg/Hurricane/blob/bca4a49cdccec3cd5e2da84022305ea16b4411fd/src/haven/MapView.java#L2305
maybe here need event coords here? like: `ev.c` ? :)

**Comment by Nightdawg** [comment]
Yeah, still working on these cursed post-merge fixes. 
Fixed this too, will push the commit soon, thanks.
